[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
media_core = { path = "../../media_core" }
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
futures.workspace = true
dotenvy.workspace = true
tauri = { version = "2.0", features = [] }
opener.workspace = true

[build-dependencies]
tauri-build = { version = "2.0", features = [] }
